# Generated by Django 4.2.7 on 2025-05-25 08:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_uploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستاورد')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات دستاورد')),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='تصویر نشان')),
                ('points_awarded', models.IntegerField(default=0, verbose_name='امتیاز')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': 'دستاوردها',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, verbose_name='شرح هزینه')),
                ('expense_date', models.DateField(verbose_name='تاریخ هزینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FutureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن ایده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'ایده',
                'verbose_name_plural': 'ایده\u200cها',
            },
        ),
        migrations.CreateModel(
            name='GithubCommitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_url', models.URLField(verbose_name='لینک Commit گیت\u200cهاب')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات لینک')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
            ],
            options={
                'verbose_name': 'لینک گیت\u200cهاب',
                'verbose_name_plural': 'لینک\u200cهای گیت\u200cهاب',
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='شرح مشکل')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='برطرف شده')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل مشکل')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_help_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست کننده')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_help_requests', to=settings.AUTH_USER_MODEL, verbose_name='حل کننده')),
            ],
            options={
                'verbose_name': 'درخواست کمک',
                'verbose_name_plural': 'درخواست\u200cهای کمک',
            },
        ),
        migrations.CreateModel(
            name='HelpRequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن پیام')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ارسال')),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.helprequest', verbose_name='درخواست کمک')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام درخواست کمک',
                'verbose_name_plural': 'پیام\u200cهای درخواست\u200cهای کمک',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='بازخورد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
            ],
            options={
                'verbose_name': 'بازخورد مدیر',
                'verbose_name_plural': 'بازخوردهای مدیر',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن پیام')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک مربوطه')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('notification_type', models.CharField(choices=[('task_deadline', 'مهلت وظیفه'), ('report_due', 'زمان گزارش کار'), ('task_approved', 'وظیفه تایید شد'), ('task_rejected', 'وظیفه رد شد'), ('new_feedback', 'بازخورد جدید'), ('new_help_request', 'درخواست کمک جدید'), ('new_achievement', 'دستاورد جدید')], max_length=50, verbose_name='نوع اعلان')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات پروژه')),
                ('deadline', models.DateField(verbose_name='مهلت انجام پروژه')),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('completed', 'انجام شده'), ('finished', 'تمام شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان وظیفه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات وظیفه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='مهلت انجام وظیفه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('needs_review', 'نیاز به بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده توسط مدیر')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید/رد')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد شدن')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('assigned_to', models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص یافته به')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='app.task', verbose_name='وظیفه والد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ کسب')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.achievement', verbose_name='دستاورد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستاورد کاربر',
                'verbose_name_plural': 'دستاورد\u200cهای کاربر',
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گروه')),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
            options={
                'verbose_name': 'گروه کاربران',
                'verbose_name_plural': 'گروه\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks_completed', models.IntegerField(default=0, verbose_name='کل وظایف تکمیل شده')),
                ('on_time_completion_rate', models.FloatField(default=0.0, verbose_name='درصد تکمیل به موقع')),
                ('avg_report_frequency', models.FloatField(default=0.0, verbose_name='میانگین تناوب گزارش')),
                ('total_ideas_submitted', models.IntegerField(default=0, verbose_name='کل ایده\u200cهای ثبت شده')),
                ('total_expenses_reported', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='کل هزینه\u200cهای گزارش شده')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'متریک عملکرد کاربر',
                'verbose_name_plural': 'متریک\u200cهای عملکرد کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, verbose_name='امتیاز کل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='تاریخ گزارش')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='شرح فعالیت')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ثبت گزارش')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_work', to=settings.AUTH_USER_MODEL, verbose_name='گزارش دهنده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='app.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'گزارش کار',
                'verbose_name_plural': 'گزارش\u200cهای کار',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_report_attachments/', verbose_name='فایل')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='نوع فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.workreport', verbose_name='گزارش کار')),
            ],
            options={
                'verbose_name': 'پیوست گزارش کار',
                'verbose_name_plural': 'پیوست\u200cهای گزارش کار',
            },
        ),
        migrations.DeleteModel(
            name='uploadModel',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to_groups',
            field=models.ManyToManyField(blank=True, related_name='projects', to='app.usergroup', verbose_name='اختصاص به گروه\u200cها'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='managerfeedback',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.task', verbose_name='وظیفه'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='app.task', verbose_name='وظیفه'),
        ),
        migrations.AddField(
            model_name='githubcommitlink',
            name='work_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_links', to='app.workreport', verbose_name='گزارش کار'),
        ),
        migrations.AddField(
            model_name='futurenote',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_notes', to='app.task', verbose_name='وظیفه'),
        ),
        migrations.AddField(
            model_name='futurenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_future_notes', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده ایده'),
        ),
        migrations.AddField(
            model_name='expense',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.task', verbose_name='وظیفه'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_expenses', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده هزینه'),
        ),
    ]
