# Generated by Django 4.2.7 on 2025-05-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_achievement_expense_futurenote_githubcommitlink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workreport',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workreport',
            name='start_time',
        ),
        migrations.CreateModel(
            name='WorkTimeSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات بازه')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_spans', to='app.workreport', verbose_name='گزارش کار')),
            ],
            options={
                'verbose_name': 'بازه زمانی کار',
                'verbose_name_plural': 'بازه\u200cهای زمانی کار',
                'ordering': ['start_time'],
            },
        ),
    ]
